name: nba games stats

on:
  schedule:
    - cron: "0 14 * * *"  # 每天 UTC 14:00 執行
  workflow_dispatch:  # 手動觸發

jobs:
  run-spyder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install nba_api requests numpy pandas pytz

      - name: Run the NBA spyder
        run: python api.py

      - name: Commit games stats CSVs to repo
        run: |
          git config --global user.name "ldhejlvfl"
          git config --global user.email "3314tony@gmail.com"
          git add game_stats/*
          git commit -m "Add latest NBA game stats" || echo "No changes to commit"
          git push
